name: movies
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_native_splash: any
  flutter_screenutil: any
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: any
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: any
  retrofit: any
  retrofit_generator: any
  url_launcher: any

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
